server:
  port: 8083
spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: BGZ5179
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
      # hibernate:
      #   dialect: org.hibernate.dialect.MySQL8Dialect                above Hibernate 6 version auto detect correct SQL dialect from JDBC no need to manually MySQL8Dialect is deprecated

